apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: frontend
  ports:
  - port: 80 # The port that the service is running on in the cluster
    targetPort: 80 # The port expose by service
    nodePort: 31000
    protocol: TCP
  type: NodePort  # type of the service