replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

image:
  repository: pmv1919/angular-app
  pullPolicy: IfNotPresent
  tag: "1.0"
  containerName: angular-app
  containerPort: 80 # container will run on 80 port in cluster

service:
  type: NodePort
  nodePort: 31500
  protocol: TCP
  port: 80
  targetPort: 80




