apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    {{- include "project-1-angular.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "project-1-angular.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "project-1-angular.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.image.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
